# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
style = "sciml"
# remove_extra_newlines = false
# pipe_to_function_call = false
# short_to_long_function_def =false
# always_use_return = false
# annotate_untyped_fields_with_any = false
