name: Register Package
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version v0.1.0
        required: true
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}