name: Register Julia Package

on:
  workflow_dispatch:
    inputs:
      version:
        description: "v0.1.0"
        required: true

jobs:
  register:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git checkout v0.1.0

      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - uses: julia-actions/RegisterAction@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}